//data store for state questions
const QUESTIONS = [
    {
        number: 1,
        question: "What is the state capital of Alabama?",
        A: "Birmingham",
        B: "Auburn",
        C: "Montgomery",
        D: "Huntsville",
    },
    {
        number: 2,
        question: "What is the state capital of Alaska?",
        A: "Anchorage",
        B: "North Pole",
        C: "Homer",
        D: "Juneau",
    },
    {
        number: 3,
        question: "What is the state capital of Arizona?",
        A: "Tucson",
        B: "Phoenix",
        C: "Sedona",
        D: "Flagstaff",
    },
    {
        number: 4,
        question: "What is the state capital of Arkansas?",
        A: "Harrison",
        B: "Hot Springs",
        C: "Little Rock",
        D: "Conway",
    },
    {
        number: 5,
        question: "What is the state capital of California?",
        A: "Sacramento",
        B: "San Diego",
        C: "Los Angeles",
        D: "San Francisco",
    },
    {
        number: 6,
        question: "What is the state capital of Colorado?",
        A: "Denver",
        B: "Colorado Springs",
        C: "Boulder",
        D: "Aspen",
    },
    {
        number: 7,
        question: "What is the state capital of Connecticut?",
        A: "New Haven",
        B: "Stamford",
        C: "Bridgeport",
        D: "Hartford",
    },
    {
        number: 8,
        question: "What is the state capital of Delaware?",
        A: "Wilmington",
        B: "Newark",
        C: "Delaware City",
        D: "Dover",
    },
    {
        number: 9,
        question: "What is the state capital of Florida?",
        A: "Tallahassee",
        B: "Miami",
        C: "Orlando",
        D: "Jacksonville",
    },
    {
        number: 10,
        question: "What is the state capital of Georgia?",
        A: "Augusta",
        B: "Savannah",
        C: "Atlanta",
        D: "Athens",
    },
    {
        number: 11,
        question: "What is the state capital of Hawaii?",
        A: "Kailua",
        B: "Honolulu",
        C: "Pearl City",
        D: "Hana",
    },
    {
        number: 12,
        question: "What is the state capital of Idaho?",
        A: "Twin Falls",
        B: "Boise",
        C: "Eagle",
        D: "Meridian",
    },
    {
        number: 13,
        question: "What is the state capital of Illinois?",
        A: "Rockford",
        B: "Chicago",
        C: "Peoria",
        D: "Springfield",
    },
    {
        number: 14,
        question: "What is the state capital of Indiana?",
        A: "Fort Wayne",
        B: "Bloomington",
        C: "Indianapolis",
        D: "Evansville",
    },
    {
        number: 15,
        question: "What is the state capital of Iowa?",
        A: "Cedar Rapids",
        B: "Des Moines",
        C: "Iowa City",
        D: "Davenport",
    },
    {
        number: 16,
        question: "What is the state capital of Kansas?",
        A: "Topeka",
        B: "Kansas City",
        C: "Wichita",
        D: "Manhattan",
    },
    {
        number: 17,
        question: "What is the state capital of Kentucky?",
        A: "Louisville",
        B: "Frankfort",
        C: "Lexington",
        D: "Florence",
    },
    {
        number: 18,
        question: "What is the state capital of Louisiana?",
        A: "New Orleans",
        B: "Lafayette",
        C: "Baton Rouge",
        D: "Alexandria",
    },
    {
        number: 19,
        question: "What is the state capital of Maine?",
        A: "Portland",
        B: "Bar Harbor",
        C: "Augusta",
        D: "Camden",
    },
    {
        number: 20,
        question: "What is the state capital of Maryland?",
        A: "Annapolis",
        B: "Rockville",
        C: "Ocean City",
        D: "Baltimore",
    },
    {
        number: 21,
        question: "What is the state capital of Massachusetts?",
        A: "Boston",
        B: "Salem",
        C: "Cambridge",
        D: "Plymouth",
    },
    {
        number: 22,
        question: "What is the state capital of Michigan?",
        A: "Detroit",
        B: "Grand Rapids",
        C: "Ann Arbor",
        D: "Lansing",
    },
    {
        number: 23,
        question: "What is the state capital of Minnesota?",
        A: "Saint Paul",
        B: "Minneapolis",
        C: "Minnesota City",
        D: "Bloomington",
    },
    {
        number: 24,
        question: "What is the state capital of Mississippi?",
        A: "Laurel",
        B: "Gulfport",
        C: "Jackson",
        D: "Oxford",
    },
    {
        number: 25,
        question: "What is the state capital of Missouri?",
        A: "Jefferson City",
        B: "St. Louis",
        C: "Springfield",
        D: "Columbia",
    },
    {
        number: 26,
        question: "What is the state capital of Montana?",
        A: "Billings",
        B: "Great Falls",
        C: "Whitefish",
        D: "Helena",
    },
    {
        number: 27,
        question: "What is the state capital of Nebraska?",
        A: "Grand Island",
        B: "Lincoln",
        C: "Nebraska City",
        D: "Omaha",
    },
    {
        number: 28,
        question: "What is the state capital of Nevada?",
        A: "Las Vegas",
        B: "Carson City",
        C: "Reno",
        D: "Sparks",
    },
    {
        number: 29,
        question: "What is the state capital of New Hampshire?",
        A: "Concord",
        B: "Manchester",
        C: "Portsmouth",
        D: "Hampton",
    },
    {
        number: 30,
        question: "What is the state capital of New Jersey?",
        A: "Jersey City",
        B: "Newark",
        C: "Trenton",
        D: "Camden",
    },
    {
        number: 31,
        question: "What is the state capital of New Mexico?",
        A: "Albuquerque",
        B: "Roswell",
        C: "Las Vegas",
        D: "Santa Fe",
    },
    {
        number: 32,
        question: "What is the state capital of New York?",
        A: "Albany",
        B: "Buffalo",
        C: "Rochester",
        D: "Syracuse",
    },
    {
        number: 33,
        question: "What is the state capital of North Carolina?",
        A: "Charlotte",
        B: "Raleigh",
        C: "Wilmington",
        D: "Greensboro",
    },
    {
        number: 34,
        question: "What is the state capital of North Dakota?",
        A: "Grand Forks",
        B: "Bismarck",
        C: "Fargo",
        D: "Williston",
    },
    {
        number: 35,
        question: "What is the state capital of Ohio?",
        A: "Cincinnati",
        B: "Cleveland",
        C: "Columbus",
        D: "Dayton",
    },
    {
        number: 36,
        question: "What is the state capital of Oklahoma?",
        A: "Tulsa",
        B: "Lawton",
        C: "Oklahoma City",
        D: "Norman",
    },
    {
        number: 37,
        question: "What is the state capital of Oregon?",
        A: "Portland",
        B: "Eugene",
        C: "Salem",
        D: "Oregon City",
    },
    {
        number: 38,
        question: "What is the state capital of Pennsylvania?",
        A: "Pittsburgh",
        B: "Harrisburg",
        C: "Philadelphia",
        D: "Allentown",
    },
    {
        number: 39,
        question: "What is the state capital of Rhode Island?",
        A: "Providence",
        B: "Newport",
        C: "Warwick",
        D: "Cranston",
    },
    {
        number: 40,
        question: "What is the state capital of South Carolina?",
        A: "Charleston",
        B: "Myrtle Beach",
        C: "Columbia",
        D: "Columbia",
    },
    {
        number: 41,
        question: "What is the state capital of South Dakota?",
        A: "Sioux Falls",
        B: "Rapid City",
        C: "Aberdeen",
        D: "Pierre",
    },
    {
        number: 42,
        question: "What is the state capital of Tennessee?",
        A: "Nashville",
        B: "Memphis",
        C: "Knoxville",
        D: "Franklin",
    },
    {
        number: 43,
        question: "What is the state capital of Texas?",
        A: "Houston",
        B: "Austin",
        C: "Dallas",
        D: "Texas City",
    },
    {
        number: 44,
        question: "What is the state capital of Utah?",
        A: "Ogden",
        B: "Cedar City",
        C: "Salt Lake City",
        D: "St. George",
    },
    {
        number: 45,
        question: "What is the state capital of Vermont?",
        A: "Montpelier",
        B: "Burlington",
        C: "Stowe",
        D: "Manchester",
    },
    {
        number: 46,
        question: "What is the state capital of Virginia?",
        A: "Norfolk",
        B: "Williamsburg",
        C: "Virginia Beach",
        D: "Richmond",
    },
    {
        number: 47,
        question: "What is the state capital of Washington?",
        A: "Seattle",
        B: "Olympia",
        C: "Tacoma",
        D: "Redmond",
    },
    {
        number: 48,
        question: "What is the state capital of West Virginia?",
        A: "Morgantown",
        B: "Harpers Ferry",
        C: "Charleston",
        D: "Huntington",
    },
    {
        number: 49,
        question: "What is the state capital of Wisconsin?",
        A: "Madison",
        B: "Milwaukee",
        C: "Lake Geneva",
        D: "Wisconsin Dells",
    },
    {
        number: 50,
        question: "What is the state capital of Wyoming?",
        A: "Cody",
        B: "Gillette",
        C: "Rock Springs",
        D: "Cheyenne",
    }
];

//quiz answers
const correctAnswers = ['C', 'D', 'B', 'C', 'A', 
    'A', 'D', 'D', 'A', 'C', 'B', 'B', 'D', 'C', 'B', 
    'A', 'B', 'C', 'C', 'A', 'A', 'D', 'A', 'C', 'A', 
    'D', 'B', 'B', 'A', 'C', 'D', 'A', 'B', 'B', 'C', 
    'C', 'C', 'B', 'A', 'D', 'D', 'A', 'B', 'C', 'A', 
    'D', 'B', 'C', 'A', 'D'];